services:
  broodwar-replays-frontent:
    build: .
    ports:
      - 443:443
      - 80:80
    volumes:
      - broodwar-replays-static:/var/www/html/static/
      - broodwar-replays-certs:/etc/ssl/app-certs/
    environment:
      - NGINX_HOST=${HOST}

volumes:
  broodwar-replays-static:
    external: true
    name: broodwar-replays-static
  broodwar-replays-certs:
    external: true
    name: broodwar-replays-certs


