services:
  broodwar-replays-frontent:
    build: .
    ports:
      - localhost:8081:80
    volumes:
      - broodwar-replays-static:/var/www/html/static/
    environment:
      - NGINX_HOST=${HOST}

volumes:
  broodwar-replays-static:
    external: true
    name: broodwar-replays-static

